controller_manager:
  ros:
    # Publish all joint states
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

# Wheel Velocity Controllers
left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 200.0, i: 50.0, d: 2.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
  publish_rate: 50

right_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 200.0, i: 50.0, d: 2.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
  publish_rate: 50

# Optional: Support Wheel Controllers (for drunk wheels)
support_wheels_controller:
  type: effort_controllers/JointPositionController
  joints:
    - front_left_support_joint
    - front_right_support_joint
    - rear_left_support_joint
    - rear_right_support_joint
  pid: {p: 10.0, i: 1.0, d: 0.1}
