# Controller Manager Configuration
controller_manager:
  ros:
    # Publish all joint states
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

# Joint State Controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# Optional: Support Wheel Controllers (for support wheels)
support_wheels_controller:
  type: effort_controllers/JointPositionController
  joints:
    - front_left_support_joint
    - front_right_support_joint
    - rear_left_support_joint
    - rear_right_support_joint
  pid: {p: 10.0, i: 1.0, d: 0.1}